adv_train: false
attack:
    attack_box: false
    attack_protected: true
    attack_right: false
    attack_type: pgd
    epsilon: 0.0078431
    pgd_alpha: 0.003921568
    pgd_steps: 10
batch_size: 256
dataset:
    channel_means:
    - 0.4785
    - 0.4678
    - 0.3966
    channel_stds:
    - 0.2466
    - 0.2396
    - 0.2494
    channels: 3
    data_dir: ./assets/datasets
    n_classes: 4
    name: coco-animals
    resize: 224
device: cuda
epochs: 100
explicit_model_path: null
k_type_y: linear
last_hidden_dim: 1024
learning_rate: 0.0005
log_interval: 5
lr_scheduler: null
model: resnet18
model_dir: null
num_workers: 2
pretrained_model_path: null
resnet:
    norm_layer: none
run_hash: null
run_name: null
seed: 1
sigma: 5.0
split_hps:
    additional_hsic_y_x: 0
    additional_hsic_z_z: 0
    beta_step: 0
    cross_entropy_weight: 0
    hard_space_split: 0
    hsic_warmup_epochs: 0
    l_cluster_hsicx_weight: 0
    l_hsic_z_z_weight: 0
    l_shared_hsicy_weight: 0
    lambda_cluster: 0
    lambda_shared: 0
    lambda_x: 0
    lambda_x_shared: 0
    lambda_y: 0
    lambda_y_cluster: 0
    update_betas_per_epoch: 0
training_type: standard
val_split_ratio: 0.2
verbose: 0
wandb:
    enabled: true
    entity: teodav-northeastern-university
    project: Clean Training [Cleaned Project]
    save_dir: ./assets/logs
    tag: standard
warmup: false
warmup_epochs: 0
warmup_lr: 1.0e-17
