accelerator: auto
adv_train: false
attack:
    attack_box: false
    attack_protected: false
    attack_right: false
    attack_type: pgd
    epsilon: 0.0078431
    pgd_alpha: 0.003921568
    pgd_steps: 10
batch_size: 32
checkpoint:
    ckpt_dir: /mnt/data/skabriia00dm/adv/assets/checkpoints
    enabled: true
    mode: max
    monitor: val/ACC
    resume_from_checkpoint: null
class_weight_method: balanced
compute_LC: false
dataset:
    channel_means:
    - 0.7232
    - 0.6168
    - 0.5692
    channel_stds:
    - 0.1668
    - 0.175
    - 0.1955
    channels: 3
    data_dir: /mnt/data/skabriia00dm/adv/assets/datasets
    n_classes: 3
    name: isic2017
    resize: 224
device: cuda
devices: 1
epochs: 50
explicit_model_path: null
group_name: null
hbar_hps:
    hsic_layer_decay: null
    k_type_y: null
    lambda_x: null
    lambda_y: null
    sigma: null
    smooth: null
    smooth_eps: null
    xentropy_weight: null
k_type_y: linear
last_hidden_dim: 1024
learning_rate: 0.0001
log_interval: 1
lr_scheduler: null
model: resnet50
model_dir: null
momentum: 0.9
num_workers: 10
optimizer: adam
pretrained_model_path: null
resnet:
    norm_layer: null
    weights: imagenet
run_hash: null
run_name: null
seed: 1
sigma: 5.0
sparsity_lambda: 0
sparsity_type: null
split_hps:
    additional_hsic_y_x: 0
    additional_hsic_z_z: 0
    beta_init_sample_fraction: 0
    beta_step: 0
    beta_update_step_fraction: 0
    beta_warmup_epochs: 0
    cross_entropy_weight: 0
    hard_space_split: 0
    hsic_warmup_epochs: 0
    l_cluster_hsicx_weight: 0
    l_hsic_z_z_weight: 0
    l_shared_hsicy_weight: 0
    lambda_cluster: 0
    lambda_shared: 0
    lambda_x: 0
    lambda_x_shared: 0
    lambda_y: 0
    lambda_y_cluster: 0
    shared_space_variation: 0
    update_betas_per_epoch: 0
training_type: standard
use_class_weights: true
val_split_ratio: 0.2
verbose: 0
wandb:
    enabled: true
    entity: teodav-northeastern-university
    project: ISIC-2017
    save_dir: /mnt/data/skabriia00dm/adv/assets/logs
    tag: vanilla_c02_learning_rate=0.0001_class_weight_method=balanced
warmup: false
warmup_epochs: 0
warmup_lr: 1.0e-17
weight_decay: 0
