name: 'coco-animals'
data_dir: './assets/datasets'
subset_path: null
sample_fraction_per_class: null
resize: 224
channels: 3
n_classes: 4
channel_means: # assumes shape 224x224
  - 0.4785
  - 0.4678
  - 0.3966
channel_stds: # assumes shape 224x224
  - 0.2466
  - 0.2396
  - 0.2494  