name: 'counteranimal'
data_dir: './assets/datasets'

evaluate_mode: 'common' # common, counter
augmentation_type: 'imagenet'

subset_path: null
sample_fraction_per_class: null


resize: 224
channels: 3
n_classes: 1000
channel_means: # assumes shape 224x224
  - 0.485
  - 0.456
  - 0.406
channel_stds: # assumes shape 224x224
  - 0.229
  - 0.224
  - 0.225
